# desc: converts .csv files generated by m3utocsv(or custom) to playable m3u
# usage: python3 csvtom3u.py {filename.csv}
import sys

file = sys.argv[1]
file = open(file)
lines = file.readlines()
file.close

file = sys.argv[1].split('.')[0]
file = open(f"{file}.m3u", "x")

prefix = "#EXTINF:-1 "
tvgc = "tvg-country="
tvgg = "group-title="
channels = ""

file.write(f"#EXTM3U\n")

for line in lines:
    if len(line)<10 or line[0]=='#':
        continue
    parts = line.split(';')

    name = parts[0]
    group= parts[1]
    lang = parts[2]
    link = parts[3]

    oline = prefix
    oline+=f'{tvgc}"{lang}" '
    oline+=f'{tvgg}"{group}",'
    oline+=f"{name}"

    channels+=f"{oline}\n{link}\n"

file.write(channels)
file.close()
