# desc: converts .csv files generated by m3utocsv(or custom) to playable m3u
# usage: python3 csvtom3u.py {filename.csv}
import sys

file = sys.argv[1]
with open(file) as f:
    lines = f.readlines()

prefix = "#EXTINF:-1 "
tvgc = "tvg-country="
tvgg = "group-title="
channels = ""


for line in lines:
    if len(line)<10 or line[0]=='#':
        continue
    parts = line.split(';')

    name, group, lang, link, *_ = parts

    oline = prefix
    oline+=f'{tvgc}"{lang}" '
    oline+=f'{tvgg}"{group}",'
    oline+=f"{name}"

    channels+=f"{oline}\n{link}\n"

file = sys.argv[1].split('.')[0]
with open(f"{file}.m3u", "x") as f:
    f.write(f"#EXTM3U\n")
    f.write(channels)
